services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.1
    container_name: keycloak
    command: start-dev --import-realm
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    ports:
      - "9999:9999"
    volumes:
      - ./docker/keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json:ro
    networks:
      - app-network

  shell-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: shell-app
    ports:
      - "4200:80"
    depends_on:
      - keycloak
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
