services:
  shell-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: shell-app
    ports:
      - "4200:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
